from enum import IntEnum


class ProjectRole(IntEnum):
    ASSISTANT_PROJECT_MANAGER = 11
    ASSISTANT_SITE_SUPERVISOR = 8
    CADET = 6
    CONSTRUCTION_MANAGER = 21
    CONTRACT_ADMINISTRATORS = 7
    CONTRACTS_MANAGER = 9
    DESIGN = 0
    DIGITAL_ENGINEERING = 2
    GRADUATES = 16
    HEALTH_SAFETY = 5
    PROJECT_COORDINATORS = 4
    PROJECT_MANAGER = 17
    PROJECT_SUPPORT = 19
    QUALITY = 1
    SENIOR_CONTRACT_ADMINISTRATOR = 18
    SENIOR_PROJECT_COORDINATOR = 3
    SENIOR_PROJECT_MANAGER = 13
    SENIOR_SITE_MANAGER = 20
    SENIOR_SITE_SUPERVISOR = 12
    SERVICES = 14
    SITE_MANAGER = 10
    SITE_SUPERVISORS = 15

    def __str__(self) -> str:
        return str(self.value)
